Models/Domain/Restaurant.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using System;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using TheRandomFork.Models.ViewModels;

namespace TheRandomFork.Models.Domain
{
    public class Restaurant
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Road { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
        public RestaurantType Type { get; set; }
        public string Homepage { get; set; }
        public virtual ICollection<RestaurantClosedDay> ClosedDays { get; set; }
        public virtual ICollection<RestaurantHistoryEntry> History { get; set; }
        public RestaurantViewModel ToViewModel(List<RestaurantClosedDay> ClosedDays)
        {
            var restaurantViewModle = new RestaurantViewModel();

            restaurantViewModle.Name = Name;
            restaurantViewModle.Road = Road;
            restaurantViewModle.City = City;
            restaurantViewModle.PhoneNumber = PhoneNumber;
            restaurantViewModle.Type = Type;
            restaurantViewModle.Homepage = Homepage;
            restaurantViewModle.Id = Id;

            if(ClosedDays != null)
            {
                if (ClosedDays.Any(x => x.ClosedDay == DayOfWeek.Monday)) restaurantViewModle.Monday = true;
                if (ClosedDays.Any(x => x.ClosedDay == DayOfWeek.Tuesday)) restaurantViewModle.Tuesday = true;
                if (ClosedDays.Any(x => x.ClosedDay == DayOfWeek.Wednesday)) restaurantViewModle.Wednesday = true;
                if (ClosedDays.Any(x => x.ClosedDay == DayOfWeek.Thursday)) restaurantViewModle.Thursday = true;
                if (ClosedDays.Any(x => x.ClosedDay == DayOfWeek.Friday)) restaurantViewModle.Friday = true;
            }
            return restaurantViewModle;
        }

        public void FromViewModel(RestaurantViewModel viewModel)
        {
            Name = viewModel.Name;
            Road = viewModel.Road;
            City = viewModel.City;
            PhoneNumber = viewModel.PhoneNumber;
            Type = viewModel.Type;
            Homepage = viewModel.Homepage;

            // Generate new collection of the new days. 
            // Interate afterwards thow every checkbox, not that nice... :-(
            ClosedDays = new Collection<RestaurantClosedDay>();
            if (viewModel.Monday)
            {
                var closedDay = new RestaurantClosedDay();
                closedDay.RestaurantId = Id;
                closedDay.ClosedDay = DayOfWeek.Monday;
                ClosedDays.Add(closedDay);
            }
            if (viewModel.Tuesday)
            {
                var closedDay = new RestaurantClosedDay();
                closedDay.RestaurantId = Id;
                closedDay.ClosedDay = DayOfWeek.Tuesday;
                ClosedDays.Add(closedDay);
            }
            if (viewModel.Wednesday)
            {
                var closedDay = new RestaurantClosedDay();
                closedDay.RestaurantId = Id;
                closedDay.ClosedDay = DayOfWeek.Wednesday;
                ClosedDays.Add(closedDay);
            }
            if (viewModel.Thursday)
            {
                var closedDay = new RestaurantClosedDay();
                closedDay.RestaurantId = Id;
                closedDay.ClosedDay = DayOfWeek.Thursday;
                ClosedDays.Add(closedDay);
            }
            if (viewModel.Friday)
            {
                var closedDay = new RestaurantClosedDay();
                closedDay.RestaurantId = Id;
                closedDay.ClosedDay = DayOfWeek.Friday;
                ClosedDays.Add(closedDay);
            }
        }
    }

    public enum RestaurantType { FastFood, Italian, Asia, Swiss, Indian, MiddleClass, Others }
}

Models/ViewModels/RestaurantViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using TheRandomFork.Models.Domain;

namespace TheRandomFork.Models.ViewModels
{
    // Pass the information from the view to the class behind in the DB
    public class RestaurantViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Road { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
        public RestaurantType Type { get; set; }
        public string Homepage { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }

        public Restaurant ToDomainModel()
        {
            var restaurantDomainModle = new Restaurant();
            restaurantDomainModle.Id = Id;
            restaurantDomainModle.Name = Name;
            restaurantDomainModle.Road = Road;
            restaurantDomainModle.City = City;
            restaurantDomainModle.PhoneNumber = PhoneNumber;
            restaurantDomainModle.Type = Type;
            restaurantDomainModle.Homepage = Homepage;
            return restaurantDomainModle;
        }

        public void FromDomainModel(Restaurant restaurant)
        {
            Id = restaurant.Id;
            Name = restaurant.Name;
            Road = restaurant.Road;
            City = restaurant.City;
            PhoneNumber = restaurant.PhoneNumber;
            Type = restaurant.Type;
            Homepage = restaurant.Homepage;
        }
    }
}

Pages/Restaurants/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TheRandomFork.Data;
using TheRandomFork.Models.ViewModels;
using static System.Net.Mime.MediaTypeNames;

namespace TheRandomFork.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly RandomForkDbContext dbContext;
        [BindProperty]
        public RestaurantViewModel updateRestaurant { get; set; }
        public EditModel(RandomForkDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet(Guid id)
        {
            var restaurant = dbContext.Restaurants.Find(id);

            // Query to get all closed days of this restaurant
            var closedDayQuery = dbContext.ClosedDays.Where(x => x.RestaurantId == id);

            if (restaurant != null)
            {
                var closedDays = closedDayQuery.ToList();
                updateRestaurant = restaurant.ToViewModel(closedDays);
            }
        }

        public IActionResult OnPost(Guid id) 
        {
            if (updateRestaurant != null)
            {
                var existingRestaurant = dbContext.Restaurants.Find(id);
                if (existingRestaurant != null)
                {
                    // First delete all entries with the restaurant id. To be sure no others are left
                    dbContext.ClosedDays.RemoveRange(dbContext.ClosedDays.Where(x => x.RestaurantId == id));
 
                    // No update the entry and model
                    existingRestaurant.FromViewModel(updateRestaurant);
                    dbContext.SaveChanges();
                }
             }
            return Redirect("/Restaurants/Restaurants");
        }
    }
}

Pages/Restaurants/HistoryVisit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Immutable;
using TheRandomFork.Data;
using TheRandomFork.Models.Domain;
using TheRandomFork.Models.ViewModels;

namespace TheRandomFork.Pages.Restaurants
{
    public class HistoryVisitModel : PageModel
    {
        public List<String> restaurantNames = new();
        public List<DateTime> restaurantVisits = new();
        public List<Guid> restaurantIds = new();

        private readonly RandomForkDbContext dbContext;
        public HistoryVisitModel(RandomForkDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet()
        {
            // Get the restaurant history with Linq query
            var historyList = dbContext.RestaurantHistory.Select(x => new { Name = x.Restaurant.Name, VisitDate= x.VisitDateTime, VisitId = x.Id});

            historyList = historyList.OrderByDescending(x => x.VisitDate);

            foreach (var obj in historyList)
            {
                restaurantNames.Add(obj.Name);
                restaurantVisits.Add(obj.VisitDate);
                restaurantIds.Add(obj.VisitId);
            }
        }

        public IActionResult OnPostDelete(Guid id)
        {
            var historyEvent = dbContext.RestaurantHistory.Find(id);
            if (historyEvent != null)
            {
                dbContext.RestaurantHistory.Remove(historyEvent);
                dbContext.SaveChanges();
            }
            return RedirectToAction("Get");
        }
    }
}

Pages/Restaurants/Restaurants.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheRandomFork.Data;
using TheRandomFork.Models.Domain;
using TheRandomFork.Models.ViewModels;
using TheRandomFork.Services;

namespace TheRandomFork.Pages
{
    public class RestaurantModel : PageModel
    {
        public List<RestaurantViewModel> restaurants = new();
        private readonly RandomForkDbContext dbContext;

        [BindProperty]
        public RestaurantViewModel newRestaurant { get; set; } = new();
        public RestaurantModel(RandomForkDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public void OnGet()
        {
            var restaurantsDb = dbContext.Restaurants.ToList();
            // Reset the list
            restaurants.Clear();
            foreach (var restaurant in restaurantsDb)
            { // Transform all to the view model
                restaurants.Add(restaurant.ToViewModel(null));
            }
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            dbContext.Restaurants.Add(newRestaurant.ToDomainModel()); 
            dbContext.SaveChanges();
            return RedirectToAction("Get");
        }
        public IActionResult OnPostDelete(Guid id)
        {
            var existingRestaurant = dbContext.Restaurants.Find(id);
            if(existingRestaurant != null)
            {
                dbContext.Restaurants.Remove(existingRestaurant);
                dbContext.SaveChanges();
            }
            return RedirectToAction("Get");
        }
    }
}

Pages/Restaurants/Select.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using TheRandomFork.Data;
using TheRandomFork.Models.Domain;
using TheRandomFork.Models.ViewModels;

namespace TheRandomFork.Pages.Restaurants
{
    public class SelectModel : PageModel
    {
        private const int RESTAURANTS_TO_IGNORE_FROM_HISTORY = 5;

        private readonly RandomForkDbContext dbContext;
        public RestaurantViewModel Restaurant{ get; set; } = new RestaurantViewModel();
        public SelectModel(RandomForkDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
    
        public void OnGet(Guid? id)
        {
            if (id != null)
            {
                var existingRestaurant = dbContext.Restaurants.Find(id);
                if (existingRestaurant != null)
                {
                    Restaurant.FromDomainModel(existingRestaurant);
                }
            }
        }
        public IActionResult OnPostSaveRestaurant(Guid id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var restaurantHistory = new RestaurantHistoryEntry();
            restaurantHistory.RestaurantId = id;
            restaurantHistory.VisitDateTime = DateTime.Now;
            dbContext.RestaurantHistory.Add(restaurantHistory);
            dbContext.SaveChanges();

            ViewData["Message"] = "History updated, enjoy the meal!!!";
            return Page();
        }

        public IActionResult OnPostSelectRestaurant()
        {
            return OnPost();
        }

        public IActionResult OnPost()
        {
            // Query to order and just take the first fife, they needs to be ignored afterwards from the restaurant list
            var historyQuery = dbContext.RestaurantHistory
                .OrderByDescending(x => x.VisitDateTime)
                .Select(x => x.RestaurantId)
                .Take(RESTAURANTS_TO_IGNORE_FROM_HISTORY);

            DayOfWeek wk = DateTime.Today.DayOfWeek;

            // Query to select all restaurants which are closed today
            var closedDaysQuery = dbContext.ClosedDays
                .Where(x => x.ClosedDay == wk)
                .Select(x => x.RestaurantId);
                
            // Query to use just restaurants which are not in the query from above
            var randomRestaurants = dbContext.Restaurants
                .Where(x => !historyQuery.Contains(x.Id) && !closedDaysQuery.Contains(x.Id));

            var cnt = randomRestaurants.Count();

            if (cnt > 0)
            {
                var restaurant = randomRestaurants.Skip(Random.Shared.Next(cnt)).FirstOrDefault();
                if (restaurant != null)
                {
                    return Redirect($"/Restaurants/Select/{restaurant.Id}");
                }
            }else
            {
                ViewData["Message"] = "No restaurant available";
            }
            return Page();
        }
    }
}

Pages/Restaurants/Edit.cshtml
@page "{id:Guid}"
@using TheRandomFork.Models.Domain
@model TheRandomFork.Pages.Restaurants.EditModel
@{
    ViewData["Title"] = "Restaurant";
}

<h1>Restaurant List, Update</h1>
    <form method="post" class="card p-3" asp-route-id="@Model.updateRestaurant.Id">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
        <label>Name</label>
        <input type="text" asp-for="updateRestaurant.Name" class="mr-5">
        <label>Road</label>
        <input type="text" asp-for="updateRestaurant.Road" class="mr-5">
        <label>City</label>
        <input asp-for="updateRestaurant.City" class="mr-5" />
    </div>
    <div class="form-group mb-0 align-middle">
        <label>Phone number</label>
        <input asp-for="updateRestaurant.PhoneNumber" class="mr-5" />
        <label>Type</label>
        <select asp-for="updateRestaurant.Type" asp-items="Html.GetEnumSelectList<RestaurantType>()" class="mr-5"></select>
        <label>Homepage</label>
        <input asp-for="updateRestaurant.Homepage" class="mr-5" />
    </div>
    <div class="form-group mb-0 align-middle">
        <h5> Restaurant closed at: </h5>
    </div>
    <div class="form-group mb-0 align-middle">
        <label >Monday: </label>
        <input asp-for="updateRestaurant.Monday" type="checkbox" checked=@Model.updateRestaurant.Monday>
        <label> Thuesday: </label>
        <input asp-for="updateRestaurant.Tuesday" type="checkbox" checked=@Model.updateRestaurant.Tuesday>
        <label> Wednesday: </label>
        <input asp-for="updateRestaurant.Wednesday" type="checkbox" checked=@Model.updateRestaurant.Wednesday>
        <label> Thursday: </label>
        <input asp-for="updateRestaurant.Thursday" type="checkbox" checked=@Model.updateRestaurant.Thursday>
        <label> Friday: </label>
        <input asp-for="updateRestaurant.Friday" type="checkbox" checked=@Model.updateRestaurant.Friday>
        <button class="btn btn-primary">Update</button>
    </div>
</form>

Pages/Restaurants/HistoryVisit.cshtml
@page
@model TheRandomFork.Pages.Restaurants.HistoryVisitModel
@{
    ViewData["Title"] = "Restaurant Visits";
}

<h1>History of the restaurants</h1>
<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">When</th>
            <th scope="col"> </th>
        </tr>
    </thead>
    @for (var i = 0; i< Model.restaurantNames.Count; i++)
    {
        <tr>
            <td>@Model.restaurantNames[i]</td>
            <td>@Model.restaurantVisits[i]</td>
            <td>
                <form method="post" asp-page-handler="Delete" asp-route-id="@Model.restaurantIds[i]">
                    <button class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

Pages/Restaurants/Restaurants.cshtml
@page
@using TheRandomFork.Models.Domain
@model TheRandomFork.Pages.RestaurantModel
@{
    ViewData["Title"] = "Restaurant";
}

<h1>Restaurant List</h1>
<form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
            <label asp-for="newRestaurant.Name">Name</label>
            <input type="text" asp-for="newRestaurant.Name" class="mr-5">
            <label asp-for="newRestaurant.Road">Road</label>
            <input type="text" asp-for="newRestaurant.Road" class="mr-5">
            <label asp-for="newRestaurant.City"></label>
            <input asp-for="newRestaurant.City" class="mr-5" />
    </div>
    <div class="form-group mb-0 align-middle">
            <label asp-for="newRestaurant.PhoneNumber"></label>
            <input asp-for="newRestaurant.PhoneNumber" class="mr-5" />
            <label asp-for="newRestaurant.Type">Type</label>
            <select asp-for="newRestaurant.Type" asp-items="Html.GetEnumSelectList<RestaurantType>()" class="mr-5"></select>
            <label asp-for="newRestaurant.Homepage"></label>
            <input asp-for="newRestaurant.Homepage" class="mr-5" />
            <button class="btn btn-primary">Add</button>
    </div>
</form>

<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Road</th>
            <th scope="col">City</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Type</th>
            <th scope="col">Homepage</th>
            <th scope="col"> </th>
        </tr>
    </thead>
    @foreach (var restaurant in Model.restaurants)
    {
        <tr>
            <td>@restaurant.Name</td>
            <td>@restaurant.Road</td>
            <td>@restaurant.City</td>
            <td>@restaurant.PhoneNumber</td>
            <td>@($"{restaurant.Type}")</td>
            <td><a href=@restaurant.Homepage>@restaurant.Homepage</a></td>
            <td>
                <form method="post" asp-page-handler="Delete" asp-route-id="@restaurant.Id">
                    <button class="btn btn-danger">Delete</button>
                </form>
                <a href="/Restaurants/Edit/@restaurant.Id" class="btn btn-dark">Edit</a>
            </td>
        </tr>
    }
</table>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

Pages/Restaurants/Select.cshtml
@page "{id:Guid?}"
@model TheRandomFork.Pages.Restaurants.SelectModel
@{
    ViewData["Title"] = "Restaurant select";
    var message = ViewData["message"]?.ToString();
}
<h1>
    Restaurant for Today, please press the start selection
</h1>
<form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
        <button class="btn btn-primary" asp-page-handler="SelectRestaurant">Start selection</button>
    </div>
</form>

@if(!string.IsNullOrWhiteSpace(message))
{ // Show message if available
    <div class="alert alert-success" role="alert">
        @message
    </div>
}

<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Road</th>
            <th scope="col">City</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Type</th>
            <th scope="col">Homepage</th>
            <th scope="col"> </th>
        </tr>
    </thead>
    @if (Model.Restaurant.Id != Guid.Empty)
    { // Show the restaurant if it's not empty. => It was selected randomly
        <tr>
            <td>@Model.Restaurant.Name</td>
            <td>@Model.Restaurant.Road</td>
            <td>@Model.Restaurant.City</td>
            <td>@Model.Restaurant.PhoneNumber</td>
            <td>@($"{Model.Restaurant.Type}")</td>
            <td><a href=@Model.Restaurant.Homepage>@Model.Restaurant.Homepage</a></td>
        </tr>
    }
</table>

@if (Model.Restaurant.Id != Guid.Empty)
{ // Show the button if a restaurant was randomly generated
    <form method="post" class="card p-3" >
        <input type="submit" id="btnSave" value="Select the restaurant and go to eat...." asp-page-handler="SaveRestaurant" asp-route-id="@Model.Restaurant.Id" />
    </form>
}